# Generated by Django 2.2.7 on 2019-11-08 05:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_auto_20191107_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 5, 15, 11, 395133, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
